on:
  push:
    branches:
      - main

jobs:
  release-image:
    environment: 'Apalia - Lab'
    name: build docker image
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: DockerHub login
      uses:  docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_HUB_REPO }}/craftedby-frontend:v1.0.0
